/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as PlaylistRouteImport } from './routes/playlist'
import { Route as ProbeRouteImport } from './routes/probe'
import { Route as ApiGateRouteImport } from './routes/api/gate'
import { Route as ApiHlsRouteImport } from './routes/api/hls'
import { Route as ApiInspectRouteImport } from './routes/api/inspect'
import { Route as ApiLogoRouteImport } from './routes/api/logo'
import { Route as ApiProbeRouteImport } from './routes/api/probe'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiTokenRouteImport } from './routes/api/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistRoute = PlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeRoute = ProbeRouteImport.update({
  id: '/probe',
  path: '/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGateRoute = ApiGateRouteImport.update({
  id: '/api/gate',
  path: '/api/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHlsRoute = ApiHlsRouteImport.update({
  id: '/api/hls',
  path: '/api/hls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInspectRoute = ApiInspectRouteImport.update({
  id: '/api/inspect',
  path: '/api/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoRoute = ApiLogoRouteImport.update({
  id: '/api/logo',
  path: '/api/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProbeRoute = ApiProbeRouteImport.update({
  id: '/api/probe',
  path: '/api/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenRoute = ApiTokenRouteImport.update({
  id: '/api/token',
  path: '/api/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/playlist': typeof PlaylistRoute
  '/probe': typeof ProbeRoute
  '/api/gate': typeof ApiGateRoute
  '/api/hls': typeof ApiHlsRoute
  '/api/inspect': typeof ApiInspectRoute
  '/api/logo': typeof ApiLogoRoute
  '/api/probe': typeof ApiProbeRoute
  '/api/session': typeof ApiSessionRoute
  '/api/token': typeof ApiTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/playlist': typeof PlaylistRoute
  '/probe': typeof ProbeRoute
  '/api/gate': typeof ApiGateRoute
  '/api/hls': typeof ApiHlsRoute
  '/api/inspect': typeof ApiInspectRoute
  '/api/logo': typeof ApiLogoRoute
  '/api/probe': typeof ApiProbeRoute
  '/api/session': typeof ApiSessionRoute
  '/api/token': typeof ApiTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/playlist': typeof PlaylistRoute
  '/probe': typeof ProbeRoute
  '/api/gate': typeof ApiGateRoute
  '/api/hls': typeof ApiHlsRoute
  '/api/inspect': typeof ApiInspectRoute
  '/api/logo': typeof ApiLogoRoute
  '/api/probe': typeof ApiProbeRoute
  '/api/session': typeof ApiSessionRoute
  '/api/token': typeof ApiTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/playlist'
    | '/probe'
    | '/api/gate'
    | '/api/hls'
    | '/api/inspect'
    | '/api/logo'
    | '/api/probe'
    | '/api/session'
    | '/api/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/playlist'
    | '/probe'
    | '/api/gate'
    | '/api/hls'
    | '/api/inspect'
    | '/api/logo'
    | '/api/probe'
    | '/api/session'
    | '/api/token'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/playlist'
    | '/probe'
    | '/api/gate'
    | '/api/hls'
    | '/api/inspect'
    | '/api/logo'
    | '/api/probe'
    | '/api/session'
    | '/api/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  PlaylistRoute: typeof PlaylistRoute
  ProbeRoute: typeof ProbeRoute
  ApiGateRoute: typeof ApiGateRoute
  ApiHlsRoute: typeof ApiHlsRoute
  ApiInspectRoute: typeof ApiInspectRoute
  ApiLogoRoute: typeof ApiLogoRoute
  ApiProbeRoute: typeof ApiProbeRoute
  ApiSessionRoute: typeof ApiSessionRoute
  ApiTokenRoute: typeof ApiTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe': {
      id: '/probe'
      path: '/probe'
      fullPath: '/probe'
      preLoaderRoute: typeof ProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gate': {
      id: '/api/gate'
      path: '/api/gate'
      fullPath: '/api/gate'
      preLoaderRoute: typeof ApiGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hls': {
      id: '/api/hls'
      path: '/api/hls'
      fullPath: '/api/hls'
      preLoaderRoute: typeof ApiHlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inspect': {
      id: '/api/inspect'
      path: '/api/inspect'
      fullPath: '/api/inspect'
      preLoaderRoute: typeof ApiInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logo': {
      id: '/api/logo'
      path: '/api/logo'
      fullPath: '/api/logo'
      preLoaderRoute: typeof ApiLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/probe': {
      id: '/api/probe'
      path: '/api/probe'
      fullPath: '/api/probe'
      preLoaderRoute: typeof ApiProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token': {
      id: '/api/token'
      path: '/api/token'
      fullPath: '/api/token'
      preLoaderRoute: typeof ApiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  PlaylistRoute: PlaylistRoute,
  ProbeRoute: ProbeRoute,
  ApiGateRoute: ApiGateRoute,
  ApiHlsRoute: ApiHlsRoute,
  ApiInspectRoute: ApiInspectRoute,
  ApiLogoRoute: ApiLogoRoute,
  ApiProbeRoute: ApiProbeRoute,
  ApiSessionRoute: ApiSessionRoute,
  ApiTokenRoute: ApiTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
